#include <bits/stdc++.h>
using namespace std;
int main() {
	puts("input n");
	puts("input m");
	puts("a = 0");
	puts("b = 1");
	puts("i = 2");
	puts("j = i > n");
	puts("u = i > n");
	puts("v = i > n");
	puts("w = i > n");
	puts("x = i > n");
	puts("y = i > n");
	puts("z = i > n");
	puts("o = i > n");
	puts("p = i > n");
	puts("q = i > n");
	puts("r = i > n");
	puts("f = u != j");
	puts("if f goto 6");
	puts("f = v != j");
	puts("if f goto 6");
	puts("f = w != j");
	puts("if f goto 6");
	puts("f = x != j");
	puts("if f goto 6");
	puts("f = y != j");
	puts("if f goto 6");
	puts("f = z != j");
	puts("if f goto 6");
	puts("f = o != j");
	puts("if f goto 6");
	puts("f = p != j");
	puts("if f goto 6");
	puts("f = q != j");
	puts("if f goto 6");
	puts("f = r != j");
	puts("if f goto 6");
	puts("if j goto 135");
	puts("s = a + b");
	puts("u = a + b");
	puts("v = a + b");
	puts("w = a + b");
	puts("x = a + b");
	puts("y = a + b");
	puts("z = a + b");
	puts("o = a + b");
	puts("p = a + b");
	puts("q = a + b");
	puts("r = a + b");
	puts("f = u != s");
	puts("if f goto 38");
	puts("f = v != s");
	puts("if f goto 38");
	puts("f = w != s");
	puts("if f goto 38");
	puts("f = x != s");
	puts("if f goto 38");
	puts("f = y != s");
	puts("if f goto 38");
	puts("f = z != s");
	puts("if f goto 38");
	puts("f = o != s");
	puts("if f goto 38");
	puts("f = p != s");
	puts("if f goto 38");
	puts("f = q != s");
	puts("if f goto 38");
	puts("f = r != s");
	puts("if f goto 38");
	puts("k = s % m");
	puts("u = s % m");
	puts("v = s % m");
	puts("w = s % m");
	puts("x = s % m");
	puts("y = s % m");
	puts("z = s % m");
	puts("o = s % m");
	puts("p = s % m");
	puts("q = s % m");
	puts("r = s % m");
	puts("f = u != k");
	puts("if f goto 69");
	puts("f = v != k");
	puts("if f goto 69");
	puts("f = w != k");
	puts("if f goto 69");
	puts("f = x != k");
	puts("if f goto 69");
	puts("f = y != k");
	puts("if f goto 69");
	puts("f = z != k");
	puts("if f goto 69");
	puts("f = o != k");
	puts("if f goto 69");
	puts("f = p != k");
	puts("if f goto 69");
	puts("f = q != k");
	puts("if f goto 69");
	puts("f = r != k");
	puts("if f goto 69");
	puts("a = b");
	puts("b = k");
	puts("l = i + 1");
	puts("u = i + 1");
	puts("v = i + 1");
	puts("w = i + 1");
	puts("x = i + 1");
	puts("y = i + 1");
	puts("z = i + 1");
	puts("o = i + 1");
	puts("p = i + 1");
	puts("q = i + 1");
	puts("r = i + 1");
	puts("f = u != l");
	puts("if f goto 102");
	puts("f = v != l");
	puts("if f goto 102");
	puts("f = w != l");
	puts("if f goto 102");
	puts("f = x != l");
	puts("if f goto 102");
	puts("f = y != l");
	puts("if f goto 102");
	puts("f = z != l");
	puts("if f goto 102");
	puts("f = o != l");
	puts("if f goto 102");
	puts("f = p != l");
	puts("if f goto 102");
	puts("f = q != l");
	puts("if f goto 102");
	puts("f = r != l");
	puts("if f goto 102");
	puts("i = l");
	puts("if 1 goto 6");
	puts("output b");
	return 0;
}
